name: golangci-lint
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.26
